package com.wised.helpandsettings.enums;

public enum ReasonEnum {

    NEED_A_BREAK,
    PRIVACY_CONCERNS,
    CANT_FIND_PEOPLE,
    CREATED_SECOND_ACCOUNT,
    CANT_FIND_CONTENTS,
    TROUBLE_GETTING_STARTED,
    TROUBLE_SAVING_CONTENTS,
    CONCERNED_ABOUT_DATA,
    TOO_BUSY_DISTRACTING,
    SOMETHING_ELSE
}
